#!/bin/bash

This is a program which is going to compare two words if they are same then the word is a palindrome.
i like to  write a code which is going to check whether a number is a palindrome or not
